### ISSUE TITLE
[SEO]Create Pre-rendering for TLCEdu

### ISSUE THREAD

**Issue by dc-tonglec** [TongLeC/TLCEdu#48]
### 🚀**Overview of the feature request**

Create Pre-rendering for TLCEdu

### **Tasks to do**

https://nuxtjs.org/docs/directory-structure/content#support-static-site-generation
https://blog.csdn.net/qq_26754937/article/details/122919549

- [x] 移植VueCli到Nuxt3
- [x] 数据渲染到页面上
- [x] 多语言URL适配，带语言key的路由跳转
- [x] 静态页面生成
- [x] 文章页面动态路由实现
- [x] 文章页面动态路径生成
- [ ] 图片打包优化
- [x] Gzip打包优化
- [ ] sitemap,robots.txt

### **Time logging**
| Date | Hours |
| :--: | :---: |

**Comment by QingqinKong** [comment]
https://github.com/nuxt/image/discussions/548
![Image](https://user-images.githubusercontent.com/101536317/190098449-2ef27908-cc06-4148-ad62-6f3d9a79a2ea.png)
