### ISSUE TITLE
[SEO]Edu web pages SEO friendly refactoring research

### ISSUE THREAD

**Issue by dc-tonglec** [TongLeC/TLCEdu#49]
### 📄**Overview of the documentation request**

Come up with a solution & execution plan to refactor Edu pages to be SEO friendly.

Options:

- Pre-rendering
- Static HTML
- Others?
- Static Site Generation (SSG)
### **Tasks to do**

![Image](https://user-images.githubusercontent.com/101536317/188414565-87cdc52a-d360-4f3e-8a59-cb111f2207bf.png)
There is static hosting option in nuxt.
Nuxt 同时可以生成SSR和SSG

### **Time logging**
| Date | Hours |
| :--: | :---: |

**Comment by QingqinKong** [comment]
这里是普遍的静态网站生成解决方案Static Site Generation (SSG)
https://jamstack.org/generators/

**Comment by dc-tonglec** [comment]
Now it is pre-rendered with Nuxt
