### ISSUE TITLE
Article reading page has too many tabs in mobile view port

### ISSUE THREAD

**Issue by dc-tonglec** [TongLeC/TLCEdu#54]
### 🐞Current Behavior:
Article reading page has too many tabs in mobile view port
![image](https://user-images.githubusercontent.com/85365077/189014849-7e4e9628-074d-461d-a0e8-c3a78523f530.png)

### Time logging:
| Date | Hours |
| :--: | :---: |

**Comment by jia-rong-lu** [comment]
#58
