### ISSUE TITLE
edu SEO and fix some bugs

### ISSUE THREAD

**Issue by jia-rong-lu** [TongLeC/TLCEdu#56]
### 🐞Current Behavior:

- [x] 每个页面语义化标签
- [x] 每个页面<title>总结（需要清心老师提供）
- [x] 每个页面主要内容总结（需要清心老师提供），用来写
`<meta name="description" content="xxxxx“>`
- [x] 所有图片使用 alt 属性（需要清心老师提供）。为图片提供说明性文件名和 alt 属性说明
- [x] edu 多语言遗漏项
- [x] 首页和教育践谈 video 优化 
- [x] 图片压缩

### Time logging:
| Date | Hours |
| :--: | :---: |

**Comment by dc-tonglec** [comment]
Potential keywords
![image](https://user-images.githubusercontent.com/85365077/189020027-ef2d2b45-9b3f-4865-bc97-43c62f533a8e.png)

**Comment by dc-tonglec** [comment]
We'd better to come up with a SEO doc base on the Google SEO items. https://developers.google.com/search/docs/advanced/appearance/overview
