### ISSUE TITLE
[BUG] Some improvement

### ISSUE THREAD

**Issue by QingqinKong** [TongLeC/TLCEdu#59]
### 🐞Current Behavior:

![image](https://user-images.githubusercontent.com/101536317/189261199-4f73e6e5-4811-4a91-8019-9cf610d3cf74.png)
![image](https://user-images.githubusercontent.com/101536317/189261233-f77d8a93-ff17-460e-91b1-a37fb8f4f007.png)

需要整块可以点击
### Time logging:
| Date | Hours |
| :--: | :---: |

**Comment by jia-rong-lu** [comment]
#62
