### ISSUE TITLE
[BUG] Translation should be consistent across the page

### ISSUE THREAD

**Issue by dc-tonglec** [TongLeC/TLCEdu#73]
### 🐞Current Behavior:
Currently, tile, meta description etc on the hant page is not translated to hans.
![image](https://user-images.githubusercontent.com/85365077/191393355-b5a33558-d4ca-4af7-89ce-a5e620ea5fb8.png)

### Expected Behavior:
We should translation all the content in the page. Including title, meta data, etc.

### Time logging:
| Date | Hours |
| :--: | :---: |

**Comment by QingqinKong** [comment]
In <script setup>
const { t } = useI18n();
useHead({
  title: t("msg.originalArticle"),
